# recreate:  docker-compose up -d --force-recreate --build
# restart: docker-compose restart
# stop: docker-compose stop
# start: docker-compose start
# work with php artisan : docker exec -it c-php bash
version: '3'


#NETWORK
networks:
  myblog-network:
    driver: bridge


#SERVICES
services:
  # php fpm
  my-php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: c-php
    networks:
      - myblog-network
    volumes:
      - .:/home/www/mysite
      - ./docker/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    working_dir: /home/www/mysite
    # RUN WORKER IN LARAVEL
    environment:
      #for debug
      PHP_EXTENSION_XDEBUG: 1
      PHP_IDE_CONFIG: "serverName=docker_local_dev_myblog"
      XDEBUG_CONFIG: "remote_host=192.168.1.112"

  # web-server
  my-httpd:
    image: httpd:latest
    container_name: c-httpd
    networks:
      - myblog-network
    volumes:
      - .:/home/www/mysite
      - ./docker/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./docker/httpd/hosts:/etc/hosts
    ports:
      - "8080:80"
      - "443:443"
    working_dir: /home/www/mysite

  # database
  my-sql:
    image: mysql:5.7
    container_name: c-mysql
    networks:
      - myblog-network
    command: --disable-partition-engine-check
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: laravel
    volumes:
      - ./docker_db_storage:/var/lib/mysql
    ports:
      - "3306:3306"